# Generated by Django 4.2.1 on 2023-05-31 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentplace.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('evidence_img', models.TextField(blank=True)),
                ('evidence_video', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentplace.category')),
                ('offerer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentplace.user')),
            ],
        ),
        migrations.CreateModel(
            name='HiredService',
            fields=[
                ('id_hired_service', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('request_date', models.DateField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentplace.user')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentplace.service')),
            ],
        ),
    ]
