# Generated by Django 4.2.1 on 2023-05-30 01:59

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_roles(apps, schema_editor):
    Rol = apps.get_model('talentplace', 'Rol')
    Rol.objects.bulk_create([
        Rol(rol_name='OFERTANTE'),
        Rol(rol_name='SOLICITANTE'),
        Rol(rol_name='ADMIN')
    ])

def create_admin(apps, schema_editor):
    User = apps.get_model('talentplace', 'User')
    Rol = apps.get_model('talentplace', 'Rol')
    User.objects.bulk_create([
        User(username='admin',
             name='admin',
             lastname='admin',
             birthdate='2000-01-01',
             phone='3521676543',
             gender='male',
             email='talentplac3@gmail.com',
             password=make_password('admin'),
             rol_id=Rol.objects.get(pk=3))
    ])

def create_categories(apps, schema_editor):
    Category = apps.get_model('talentplace', 'Category')
    Category.objects.bulk_create([
        Category(category_name='TRADUCTORES'),
        Category(category_name='ARTISTAS'),
        Category(category_name='DISEÑADORES'),
        Category(category_name='MANUALIDADES')
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('talentplace', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
        migrations.RunPython(create_categories),
        migrations.RunPython(create_admin)
    ]
