# Generated by Django 4.2.1 on 2023-05-30 01:59

from django.db import migrations

def create_roles(apps, schema_editor):
    Rol = apps.get_model('talentplace', 'Rol')
    Rol.objects.bulk_create([
        Rol(rol_name='OFERTANTE'),
        Rol(rol_name='SOLICITANTE'),
        Rol(rol_name='ADMIN')
    ])

def create_categories(apps, schema_editor):
    Category = apps.get_model('talentplace', 'Category')
    Category.objects.bulk_create([
        Category(category_name='TRADUCTORES'),
        Category(category_name='ARTISTAS'),
        Category(category_name='DISEÑADORES'),
        Category(category_name='MANUALIDADES')
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('talentplace', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
        migrations.RunPython(create_categories),
    ]
