# Generated by Django 4.2.1 on 2023-05-29 00:53

from django.db import migrations

def create_roles(apps, schema_editor):
    Rol = apps.get_model('talentplace', 'Rol')
    Rol.objects.bulk_create([
        Rol(name='OFERTANTE'),
        Rol(name='SOLICITANTE')
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('talentplace', '0002_category_rol_alter_user_rol'),
    ]

    operations = [
        # Otras operaciones de migración si las hay
        migrations.RunPython(create_roles),
    ]
