# Generated by Django 4.2.1 on 2023-05-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talentplace', '0003_create_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='id_category',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='id',
            new_name='id_rol',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='name',
            new_name='rol_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='id_user',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('evidence_img', models.TextField(blank=True)),
                ('evidence_video', models.TextField(blank=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentplace.category')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedService',
            fields=[
                ('id_offered_service', models.AutoField(primary_key=True, serialize=False)),
                ('offerer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentplace.user')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentplace.service')),
            ],
        ),
        migrations.CreateModel(
            name='HiredService',
            fields=[
                ('id_hired_service', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('request_date', models.DateField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentplace.user')),
                ('offered_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentplace.offeredservice')),
            ],
        ),
    ]
