# Generated by Django 4.2.1 on 2023-05-29 19:55

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('talentplace', 'Category')
    Category.objects.bulk_create([
        Category(category_name='TRADUCTORES'),
        Category(category_name='ARTISTAS'),
        Category(category_name='DISEÑADORES'),
        Category(category_name='MANUALIDADES')
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('talentplace', '0004_rename_name_category_category_name_and_more'),
    ]

    operations = [
         migrations.RunPython(create_categories),
    ]
